# Generated by Django 3.2.9 on 2022-03-18 05:32

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('photo', models.ImageField(upload_to=blog.models.Posts.get_file_path)),
                ('title_fb', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('autor', models.CharField(default='BrunoOrozco', max_length=20)),
                ('fecha', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_post', to='blog.categorias')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
